---
- name: Copy local manifest to bastion host
  copy:
    src: "{{ aap_manifest_file_local }}"
    dest: "{{ aap_manifest_file_bastion }}"
    mode: '0600'
  when: not aap_manifest_download | bool

- name: Check manifest file on bastion host
  stat:
    path: "{{ aap_manifest_file_bastion }}"
  register: manifest_file
  when: aap_manifest_download | bool

- name: Download manifest from Red Hat Customer Portal
  redhat.satellite.redhat_manifest:
    username: "{{ aap_rhsm_username }}"
    password: "{{ aap_rhsm_password }}"
    uuid: "{{ aap_manifest_uuid }}"
    path: "{{ aap_manifest_file_bastion }}"
    state: present
  changed_when: true
  when:
    - aap_manifest_download | bool
    - not manifest_file.stat.exists

- name: Change manifest file permissions
  file:
    path: "{{ aap_manifest_file_bastion }}"
    mode: '0600'

- name: Upload manifest to automation controller
  ansible.controller.license:
    controller_host: https://{{ aap_install_controller_fqdn }}
    controller_username: admin
    controller_password: "{{ aap_install_admin_password }}"
    validate_certs: false
    manifest: "{{ aap_manifest_file_bastion }}"
