---
- name: Export AAP in-use configuration
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_oauthtoken: "{{ aap_token }}"

    export_aap_configuration: true

    gateway_configuration_filetree_create_secure_logging: false
    controller_configuration_filetree_create_secure_logging: false
    hub_configuration_filetree_create_secure_logging: false
    eda_configuration_filetree_create_secure_logging: false

    output_path: ./filetree_export
    flatten_output: true
    secrets_as_variables: false
    #organization_filter: Default

  tasks:
    - name: Remove previous export directory
      ansible.builtin.file:
        path: "{{ output_path }}"
        state: absent
      when: export_aap_configuration | bool

    - name: Export AAP configuration in filetree format
      vars:
        input_tag:
          - gateway
          - controller
          #- hub
          #- eda
      ansible.builtin.include_role:
        name: infra.aap_configuration_extended.filetree_create
        public: true
      when: export_aap_configuration | bool

    - name: Remove instance data from exported configuration
      ansible.builtin.command:
        chdir: "{{ output_path }}"
        cmd: >
          sed -i
          -e '/LICENSE:/,/INSTALL_UUID:/d'
          -e '/CLEANUP_HOST_METRICS_LAST_TS/d'
          -e '/HOST_METRIC_SUMMARY_TASK_LAST_TS/d'
          controller_settings.yaml
      changed_when: true
      when: export_aap_configuration | bool

- name: Compare AAP in-cac vs in-use configuration
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_configuration_secure_logging: false

    config_live_path: ./filetree_export
    config_repo_path: ./aap_cac

    fail_if_different: true

  tasks:
    - name: Fail if configuration directories not found
      ansible.builtin.fail:
        msg: "Configuration directory {{ item }} not found."
      loop:
        - "{{ config_live_path }}"
        - "{{ config_repo_path }}"
      when: item is not directory

    - name: Read AAP in-cac configuration
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      ansible.builtin.include_vars:
        dir: "{{ config_repo_path }}"
        ignore_unknown_extensions: true
        name: config_repo

    - name: Read list of known AAP CaC wildcard variables
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
        tasks_from: vars_only
        public: true

    - name: Combine AAP in-repo wildcard variables
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      vars:
        var_name: "{{ item | regex_replace('^(' + __aap_cac_vars | join('|') + ')_.*', '\\1') }}"
        curr_val: "{{ config_repo[item] }}"
        is_dict: "{{ curr_val is mapping }}"
        prev_val: "{{ (config_repo_merged | default({})).get(var_name)
                      | default(config_repo.get(var_name))
                      | default({} if is_dict else [], true) }}"
        config_repo_filtered: "{{ config_repo
                                  | dict2items
                                  | rejectattr('key',
                                               'match',
                                               '^(' + __aap_cac_vars | join('|') + ')_.*|.*secure_logging|^tbd_.*')
                                  | items2dict }}"
      ansible.builtin.set_fact:
        config_repo_merged: >-
          {{ config_repo_merged
             | default(config_repo_filtered, true)
             | combine({
                 var_name: (prev_val | combine(curr_val, list_merge='append', recursive=true)
                            if is_dict else
                            (prev_val + curr_val) | unique)
               }, recursive=true) }}
      loop: "{{ (config_repo | default({})).keys() | select('match', '^(' + __aap_cac_vars | join('|') + ')_.*') }}"
      when: not item.endswith('_secure_logging')

    - name: Read AAP in-use configuration
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      ansible.builtin.include_vars:
        dir: "{{ config_live_path }}"
        ignore_unknown_extensions: true
        name: config_live

    - name: Merge configurations for comparison
      ansible.builtin.set_fact:
        config_merged: "{{ (config_live | normalize_lists)
                           | ansible.builtin.combine(config_repo_merged | normalize_lists, recursive=true) }}"

    - name: Compare in-cac vs in-use configurations
      ansible.utils.fact_diff:
        before: "{{ config_merged | normalize_brackets | omit_deletions }}"
        after: "{{ config_live | normalize_lists }}"
      register: config_diff

    - name: Fail on difference if requested
      ansible.builtin.fail:
        msg: "Configurations differ."
      when:
        - config_diff is changed
        - fail_if_different | bool
