---
- name: Compare filetree configuration differences
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_oauthtoken: "{{ aap_token }}"

    controller_configuration_filetree_read_secure_logging: false
    controller_configuration_filetree_object_diff_secure_logging: false

    dir_orgs_vars: ./filetree_import
    orgs: Test Org
    env: common

    include_present_state: true
    drop_user_external_accounts: false

  roles:
    - role: infra.aap_configuration_extended.object_diff
      vars:
        controller_configuration_object_diff_tasks:
          - {name: controller_schedules, var: controller_schedules, tags: controller_schedules}
          - {name: controller_workflow_job_templates, var: controller_workflows, tags: controller_workflow_job_templates}
          - {name: controller_job_templates, var: controller_templates, tags: controller_job_templates}
          - {name: controller_roles, var: controller_roles, tags: controller_roles}
          - {name: controller_teams, var: aap_teams, tags: controller_teams}
          - {name: controller_user_accounts, var: aap_user_accounts, tags: controller_users}
          - {name: controller_host_groups, var: controller_groups, tags: controller_host_groups}
          - {name: controller_hosts, var: controller_hosts, tags: controller_hosts}
          - {name: controller_applications, var: aap_applications, tags: controller_applications}
          - {name: controller_execution_environments, var: controller_execution_environments, tags: controller_execution_environments}
          - {name: controller_inventory_sources, var: controller_inventory_sources, tags: controller_inventory_sources}
          - {name: controller_inventories, var: controller_inventories, tags: controller_inventories}
          - {name: controller_projects, var: controller_projects, tags: controller_projects}
          - {name: controller_notification_templates, var: controller_notification_templates, tags: controller_notification_templates}
          - {name: controller_credentials, var: controller_credentials, tags: controller_credentials}
          - {name: controller_credential_types, var: controller_credential_types, tags: controller_credential_types}
          - {name: controller_organizations, var: aap_organizations, tags: controller_organizations}
          - {name: controller_instance_groups, var: controller_instance_groups, tags: controller_instance_groups}
    #- role: infra.aap_configuration.dispatch
