---
- name: Apply filetree configuration structure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_oauthtoken: "{{ aap_token }}"

    controller_configuration_filetree_read_secure_logging: false

    dir_orgs_vars: ./filetree_import
    orgs: Test Org
    env: common

  roles:
    - infra.aap_configuration_extended.filetree_read
    - infra.aap_configuration.dispatch
