---
- name: Create filetree configuration structure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_oauthtoken: "{{ aap_token }}"

    controller_configuration_filetree_create_secure_logging: false

    output_path: ./filetree_export
    flatten_output: false

  roles:
    - name: infra.aap_configuration_extended.filetree_create
      # For now, see https://github.com/redhat-cop/aap_configuration_extended/issues/198
      vars:
        input_tag:
          - gateway
          - controller
          - eda
