---
- name: Export AAP configuration in filetree format
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_oauthtoken: "{{ aap_token }}"

    gateway_configuration_filetree_create_secure_logging: false
    controller_configuration_filetree_create_secure_logging: false
    hub_configuration_filetree_create_secure_logging: false
    eda_configuration_filetree_create_secure_logging: false

    output_path: ./filetree_export
    flatten_output: false

  roles:
    - name: infra.aap_configuration_extended.filetree_create
      vars:
        input_tag:
          - gateway
          - controller
          - hub
          #- eda
