---
- name: Export AAP configuration in filetree format
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_configuration_secure_logging: false

    output_path: ./filetree_export
    flatten_output: false
    omit_id: true

  roles:
    - role: infra.aap_configuration_extended.filetree_create
      vars:
        input_tag:
          - gateway
          - controller
          # - hub
          # - eda
