---
- name: Configure AAP webhooks in GitHub repositories
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    hostname: "{{ aap_hostname | regex_replace('^https?://', '') }}"

    # These should come from vault
    # use either or, prefer token
    # username: "{{ aap_username }}"
    # password: "{{ aap_password }}"
    token: "{{ aap_token }}"

    # GitHub parameters
    # github_api: github.example.com/api/v3
    github_api: api.github.com
    github_token: "{{ lookup('file', lookup('env', 'PWD') + '/github_token.txt') }}"
    github_repos:
      - myllynen/aap-automation

    # Delete stale GitHub AAP webhook
    github_delete_stale_aap_hooks: true

  tasks:
    - name: Get list of job templates
      #    host=hostname, username=username, password=password, verify_ssl=false,
      ansible.builtin.set_fact:
        aap_job_templates: >-
          {{ query('ansible.platform.gateway_api', 'api/controller/v2/job_templates/',
                   host=hostname, oauth_token=token, verify_ssl=false,
                   query_params={'order_by': 'name'},
                   return_all=true, max_objects=10000) }}

    - name: Fetch webhook keys for webhook enabled job templates
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      ansible.builtin.uri:
        url: "https://{{ hostname }}/api/controller/v2/job_templates/{{ item.id }}/webhook_key/"
        # url_username: "{{ username }}"
        # url_password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: GET
        headers:
          Authorization: Bearer {{ token }}
        status_code:
          - 200
      register: aap_webhook_keys
      loop: "{{ aap_job_templates | selectattr('webhook_service', 'defined') | selectattr('webhook_service') }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Display job template webhook URLs and keys
      vars:
        hide_key: "{{ true if not aap_jt_hooks_debug | default(false) | bool or
                              aap_configuration_secure_logging | default(false) else false }}"
      ansible.builtin.debug:
        msg: |
          Job Template : {{ item.item.id }} / {{ item.item.name }}
          Service      : {{ item.item.webhook_service }}
          Webhook URL  : https://{{ hostname }}{{ item.item.related.webhook_receiver }}
          Webhook Key  : {{ '$REDACTED$' if hide_key else item.json.webhook_key }}
      loop: "{{ aap_webhook_keys.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    # Comment out to enable GitHub AAP webhook updates
    - name: End play
      ansible.builtin.meta: end_play

    - name: Fetch existing GitHub webhooks for repositories
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      ansible.builtin.uri:
        url: https://{{ github_api }}/repos/{{ item }}/hooks
        method: GET
        headers:
          Authorization: Bearer {{ github_token }}
        status_code:
          - 200
      register: existing_hooks
      loop: "{{ github_repos }}"

    - name: Delete stale GitHub AAP webhooks
      vars:
        target_urls: >-
          {{ aap_webhook_keys.results
             | map(attribute='item.related.webhook_receiver')
             | map('regex_replace', '^', 'https://' + hostname) }}
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      ansible.builtin.uri:
        url: https://{{ github_api }}/repos/{{ item.0.item }}/hooks/{{ item.1.id }}
        method: DELETE
        headers:
          Authorization: Bearer {{ github_token }}
        status_code:
          - 204
      changed_when: true
      loop: "{{ existing_hooks.results | subelements('json', skip_missing=True) }}"
      loop_control:
        label: "{{ item.0.item }} -> {{ item.1.config.url | default('no-url') }}"
      when:
        - github_delete_stale_aap_hooks | bool
        - hostname in (item.1.config.url | default(''))
        - item.1.config.url not in target_urls

    - name: Configure GitHub webhook
      vars:
        current_repo: "{{ item.0 }}"
        key_item: "{{ item.1 }}"
        target_url: https://{{ hostname }}{{ key_item.item.related.webhook_receiver }}
        repo_hooks: >-
          {{ (existing_hooks.results
              | selectattr('item', 'eq', current_repo)
              | map(attribute='json')
              | first) | default([]) }}
        existing_hook: >-
          {{ (repo_hooks
              | selectattr('config.url', 'defined')
              | selectattr('config.url', 'equalto', target_url)
              | first) | default({}, true) }}
        repo_keyword: "{{ current_repo | regex_replace('^(.*?-cac-|cac-)', '') | replace('-', '_') | lower }}"
        template_name: "{{ key_item.item.name | replace(' ', '_') | lower }}"
      no_log: "{{ aap_configuration_secure_logging | default(false) }}"
      ansible.builtin.uri:
        url: >-
          {% if existing_hook.id is defined %}
          https://{{ github_api }}/repos/{{ current_repo }}/hooks/{{ existing_hook.id }}
          {% else %}
          https://{{ github_api }}/repos/{{ current_repo }}/hooks
          {% endif %}
        method: "{{ 'PATCH' if existing_hook.id is defined else 'POST' }}"
        headers:
          Authorization: Bearer {{ github_token }}
        body_format: json
        body:
          name: web
          config:
            url: "{{ target_url }}"
            content_type: json
            secret: "{{ key_item.json.webhook_key }}"
            insecure_ssl: "1"
          events:
            - push
          active: true
        status_code:
          - 200
          - 201
      register: hook_status
      changed_when: >
        existing_hook.updated_at is not defined or
        hook_status.json.updated_at != existing_hook.updated_at
      loop: "{{ github_repos | product(aap_webhook_keys.results) }}"
      loop_control:
        label: "{{ item.0 }} -> {{ item.1.item.name }}"
      when:
        - repo_keyword in template_name
        - "'gitops' in template_name"
