---
- name: Configure AAP EE container image authentication
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    hostname: "{{ aap_hostname }}"

    # These should come from vault
    username: "{{ aap_username }}"
    password: "{{ aap_password }}"

    # List of public AAP EE images
    aap_ee_public:
      - custom/custom-base-rhel9
      - custom/custom-full-rhel9
      - ansible-automation-platform/ee-minimal-rhel9
      - ansible-automation-platform-26/ee-minimal-rhel9
      - ansible-automation-platform-26/ee-supported-rhel9

    # List of private AAP EE images
    aap_ee_private:
      - custom/custom-secret-rhel9

    container_index: /api/galaxy/pulp/api/v3/distributions/container/container/
  tasks:
    - name: Get list of AAP EE container images
      ansible.builtin.uri:
        url: https://{{ hostname + container_index }}
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: GET
      register: aap_ee_images

    - name: Configure EEs public
      ansible.builtin.uri:
        url: https://{{ hostname + item.pulp_href }}
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: PATCH
        body_format: json
        body:
          private: false
        status_code:
          - 200
          - 202
      changed_when: true
      loop: "{{ aap_ee_images.json.results | selectattr('name', 'in', aap_ee_public) }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.private != false

    - name: Configure EEs private
      ansible.builtin.uri:
        url: https://{{ hostname + item.pulp_href }}
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: PATCH
        body_format: json
        body:
          private: true
        status_code:
          - 200
          - 202
      changed_when: true
      loop: "{{ aap_ee_images.json.results | selectattr('name', 'in', aap_ee_private) }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.private != true
