---
- name: Configure AAP EE image authentication mode
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    base_url: "https://{{ aap_hostname }}"

    # These should come from vault
    username: "{{ aap_username }}"
    password: "{{ aap_password }}"

    # List of PAH EE images to update
    # Set to empty list to update all
    aap_ee_list: []
    #  - custom/custom-base-rhel9
    #  - custom/custom-full-rhel9

    # This must be either:
    # * true   - set images private and require authentcation for pulling EEs
    # * false  - set images public and thus allow unauthenticated EE image pulls
    aap_ee_private: false

    container_index: /api/galaxy/pulp/api/v3/distributions/container/container/
  tasks:
    - name: Get list of EE image containers at private automation hub
      ansible.builtin.uri:
        url: "{{ base_url + container_index }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: GET
      register: aap_ee_images

    - name: Configure EE authentication mode
      ansible.builtin.uri:
        url: "{{ base_url + item.pulp_href }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: PATCH
        body_format: json
        body:
          private: "{{ aap_ee_private }}"
        status_code:
          - 200
          - 202
      changed_when: true
      loop: "{{ aap_ee_images.json.results }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - aap_ee_list | length == 0 or item.name in aap_ee_list
        - item.private != aap_ee_private
