---
- name: Get AAP gateway API token
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    token_description: AAP gateway API token
    token_file_local: "{{ lookup('env', 'PWD') + '/aap_token.txt' }}"
    token_scope: write
  tasks:
    - name: Create new AAP gateway API token
      ansible.platform.token:
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        validate_certs: "{{ aap_validate_certs }}"
        description: "{{ token_description }}"
        scope: "{{ token_scope }}"

    - name: Store token in file
      ansible.builtin.copy:
        content: "{{ ansible_facts.aap_token.token + '\n' }}"
        dest: "{{ token_file_local }}"
        mode: '0600'

    - name: Display token file name
      ansible.builtin.debug:
        msg: >-
          PAT ({{ token_scope }}) for {{ aap_username }}
          stored at {{ ansible_host }}:{{ token_file_local }}
