---
- name: Set available execution nodes
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    hostname: "{{ aap_hostname }}"

    # These should come from vault
    username: "{{ aap_username }}"
    password: "{{ aap_password }}"

  tasks:
    - name: Get list of instances
      ansible.builtin.set_fact:
        aap_instances: >-
          {{ query('ansible.platform.gateway_api', 'api/controller/v2/instances/',
             host=hostname, username=username, password=password, verify_ssl=false,
             query_params={'order_by': 'hostname'},
             return_all=true, max_objects=10000) }}

    - name: Add execution nodes to new host group
      ansible.builtin.add_host:
        groups: aap_execution_nodes
        name: "{{ item }}"
      changed_when: false
      loop: "{{ aap_instances | selectattr('node_type', 'ne', 'control') | map(attribute='hostname') }}"

- name: Pull execution environments to execution nodes
  hosts: aap_execution_nodes
  become: false
  gather_facts: false
  vars:
    # AAP admin user
    ansible_user: admin
    # AAP admin home
    admin_home: /home/{{ ansible_user }}

    # List of AAP EE images to remove on ENs
    # NB. Do not remove the managed EE images
    aap_en_ee_remove: []

    # List of AAP PAH EE images to pull on ENs
    aap_en_ee_pull:
      - custom/custom-base-rhel9:latest
      - custom/custom-full-rhel9:latest
      #- ansible-automation-platform-26/ee-minimal-rhel9:latest
      #- ansible-automation-platform-26/ee-supported-rhel9:latest

  tasks:
    - name: Login to AAP automation hub container registry
      containers.podman.podman_login:
        registry: "{{ aap_hostname }}"
        username: "{{ aap_username }}"
        password: "{{ aap_password }}"
        tlsverify: false

    - name: Remove EE images
      environment:
        CONTAINERS_STORAGE_CONF: "{{ admin_home }}/aap/containers/storage.conf"
      containers.podman.podman_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ aap_en_ee_remove }}"

    - name: Pull EE images
      environment:
        CONTAINERS_STORAGE_CONF: "{{ admin_home }}/aap/containers/storage.conf"
      containers.podman.podman_image:
        name: "{{ aap_hostname + '/' + item | split(':') | first }}"
        tag: "{{ item | split(':') | last }}"
        force: true
        tlsverify: false
      loop: "{{ aap_en_ee_pull }}"
