---
- name: Get platform gateway token
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    token_description: Automation platform gateway token

    token_file_local: "{{ lookup('env', 'PWD') + '/aap_token.txt' }}"
  tasks:
    - name: Create new platform gateway token
      ansible.platform.token:
        aap_hostname: "{{ aap_hostname | default(omit) }}"
        aap_username: "{{ aap_username | default(omit) }}"
        aap_password: "{{ aap_password | default(omit) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        description: "{{ token_description }}"
        state: present
        scope: write

    - name: Store token in file
      ansible.builtin.copy:
        content: "{{ aap_token.token + '\n' }}"
        dest: "{{ token_file_local }}"
        mode: '0600'

    - name: Display token file name
      ansible.builtin.debug:
        msg: "Token stored on {{ ansible_host }} in '{{ token_file_local }}'."
