---
- name: Configure automation hub
  hosts: all
  become: false
  gather_facts: false
  roles:
    # Sync selected collections from external hubs
    - infra.aap_configuration.hub_collection_remote
    - infra.aap_configuration.hub_collection_repository
    - infra.aap_configuration.hub_collection_repository_sync

    # Make collections in git repos available in this hub
    - infra.aap_configuration.hub_namespace
    # https://github.com/ansible/galaxy_collection/issues/397
    - infra.aap_configuration.hub_publish

    # Sync selected EE images from external registries
    - infra.aap_configuration.hub_ee_registry
    #- infra.aap_configuration.hub_ee_registry_index
    #- infra.aap_configuration.hub_ee_registry_sync
    - infra.aap_configuration.hub_ee_repository
    - infra.aap_configuration.hub_ee_repository_sync
