---
- name: Refresh Red Hat hybrid cloud console authentication token
  hosts: bastion
  become: false
  gather_facts: false
  tasks:
    - name: Refresh token
      no_log: true
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        headers:
          accept: application/json
        body_format: form-urlencoded
        body:
          client_id: cloud-services
          grant_type: refresh_token
          refresh_token: "{{ cloud_token }}"
