---
# https://access.redhat.com/solutions/7072302
- name: Clean up orphaned AAP hub content
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    hostname: "{{ aap_hostname | regex_replace('^https?://', '') }}"

    # These should come from vault
    # use either or, prefer token
    # username: "{{ aap_username }}"
    # password: "{{ aap_password }}"
    token: "{{ aap_token }}"

  tasks:
    - name: Clean up orphaned AAP hub content
      ansible.builtin.uri:
        url: "https://{{ hostname }}/api/galaxy/pulp/api/v3/orphans/cleanup/"
        # url_username: "{{ username }}"
        # url_password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: POST
        headers:
          Authorization: Bearer {{ token }}
        body_format: json
        body:
          orphan_protection_time: 0
        status_code:
          - 200
          - 202
      changed_when: true
