---
# https://access.redhat.com/solutions/7072302
- name: Clean up orphaned AAP hub content
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    hostname: "{{ aap_hostname }}"

    # These should come from vault
    username: "{{ aap_username }}"
    password: "{{ aap_password }}"

  tasks:
    - name: Clean up orphaned AAP hub content
      ansible.builtin.uri:
        url: "https://{{ hostname }}/api/galaxy/pulp/api/v3/orphans/cleanup/"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        force_basic_auth: true
        method: POST
        body_format: json
        body:
          orphan_protection_time: 0
        status_code:
          - 200
          - 202
        validate_certs: false
      changed_when: true
