---
- name: Get AAP hub token
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    token_file_local: "{{ lookup('env', 'PWD') + '/pah_token.txt' }}"
  tasks:
    - name: Create new AAP hub token
      ansible.hub.ah_token:
        aap_hostname: "{{ aap_hostname | default(omit) }}"
        aap_username: "{{ aap_username | default(omit) }}"
        aap_password: "{{ aap_password | default(omit) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"

    - name: Store token in file
      ansible.builtin.copy:
        content: "{{ ah_token.token + '\n' }}"
        dest: "{{ token_file_local }}"
        mode: '0600'

    - name: Display token file name
      ansible.builtin.debug:
        msg: "Token stored on {{ ansible_host }} in '{{ token_file_local }}'."
